spring:
  datasource:
    druid:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console