DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	deleted bit(1) NULL DEFAULT NULL COMMENT '删除',
	enable bit(1) NULL DEFAULT NULL COMMENT '启用',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS log_message;

CREATE TABLE log_message
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	parameter LONGTEXT(0) NULL DEFAULT NULL COMMENT '参数',
	description VARCHAR(50) NULL DEFAULT NULL COMMENT '描述',
	end_time TIMESTAMP NULL DEFAULT NULL COMMENT '结束时间',
	spend_time BIGINT(20) NULL DEFAULT NULL COMMENT '耗时',
	result LONGTEXT(0) NULL DEFAULT NULL COMMENT '结果',
	PRIMARY KEY (id)
);